zoom in: edit.zoom_in()
zoom out: edit.zoom_out()
zoom normal: key(cmd-0)

scroll up: edit.page_up()
scroll down: edit.page_down()
copy that: edit.copy()
cut that: edit.cut()
paste that: edit.paste()
undo that: edit.undo()
redo that: edit.redo()
paste match: edit.paste_match_style()
